import pyautogui as bot
import webbrowser
from time import sleep
import pyperclip


bot.press("win")
sleep(2)
bot.write("zoom")
sleep(2)
bot.press("enter")
sleep(3)
bot.click(x=688, y=60)
sleep(5)
bot.click("./imagens/novaReuniao.PNG")
sleep(5)
pyperclip.copy("Reunião Semanal da congregação Liberdade Terça e Sábado")
bot.hotkey("ctrl", "v")
sleep(3)
bot.click(x=571, y=269)
bot.write("19:00")
bot.press("down")
bot.press("enter")
sleep(2)
bot.click(x=751, y=262)
bot.write("22:00")
bot.press("down")
bot.press("enter")
sleep(2)
bot.click(x=525, y=585)
bot.hotkey("ctrl", "a")
bot.press("backspace")
sleep(2)
bot.write("001914", interval=0.25)
sleep(2)
bot.click(x=966, y=693)
sleep(2)
bot.click(x=467, y=227)

bot.hotkey("ctrl", "shift", "down")
bot.hotkey("ctrl", "shift", "down")
bot.hotkey("ctrl", "shift", "down")
bot.hotkey("ctrl", "shift", "down")
bot.hotkey("ctrl", "shift", "down")
bot.hotkey("ctrl", "shift", "down")
bot.hotkey("ctrl", "shift", "down")
bot.hotkey("ctrl", "shift", "down")
bot.hotkey("ctrl", "shift", "down")
bot.hotkey("ctrl", "shift", "down")
bot.hotkey("ctrl", "shift", "down")

sleep(2)

bot.hotkey("ctrl", "c")
webbrowser.open("https://google.com.br")
sleep(2)
webbrowser.open("https://web.whatsapp.com")
sleep(20)
bot.press("tab")
bot.press("tab")
bot.press("tab")
bot.press("tab")
bot.press("tab")
bot.press("tab")
bot.press("tab")
sleep(2)
bot.write("Operadores Som e Zoom")
sleep(4)
bot.press("enter")
sleep(2)
bot.click(x=647, y=686)
sleep(2)
bot.hotkey("ctrl", "v")
sleep(2)
bot.press("enter")
sleep(2)
bot.write("Link do zoom dessa semana! 🤖 ")
sleep(2)
bot.press("enter")
sleep(2)
bot.hotkey("ctrl", "w")
